/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.orangeplayer.playerdesktop.gui.components;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.border.BevelBorder;
import org.jaudiotagger.tag.FieldKey;
import org.muplayer.audio.AudioTag;
import org.orangeplayer.playerdesktop.R;
import org.orangeplayer.playerdesktop.sys.SessionKey;
import org.orangeplayer.playerdesktop.sys.SysUtil;

/**
 *
 * @author martin
 */
public final class CardPanel extends ItemPanel<AudioTag> {

    public CardPanel(AudioTag tag) {
        super(tag);
        initComponents();
        configUI();
        loadTrackData();
    }
    
    private void setAllBackgrounds(Color color) {
        setBackground(color);
        panelTrackInfo.setBackground(color);
        lblArtist.setBackground(color);
        lblCover.setBackground(color);
        lblTitle.setBackground(color);
        updateUI();
    }
    
    @Override
    protected void configUI() {
        Color primaryColor = Color.decode("#f5f5f5");
        Color borderColor = Color.decode("#e0e0e0");
        BevelBorder border = new BevelBorder(
                BevelBorder.RAISED, null, null, borderColor, borderColor);
        setBorder(border);
        setAllBackgrounds(primaryColor);
    }
    
    public void loadTrackData() {
        final String title = element.getTag(FieldKey.TITLE);
        final String artist = element.getTag(FieldKey.ARTIST);

        lblTitle.setText(title == null ? element.getFileSource().getName() : title);
        lblArtist.setText(artist == null ? "Desconocido" : artist);
        
        if (element.hasCover())
            lblCover.setIcon(SysUtil.getResizedIcon(new ImageIcon(element.getCoverData()), lblCover));
        else if (session.get(SessionKey.DARK_MODE, boolean.class))
            lblCover.setIcon(SysUtil.getResizedIcon(R.icons("dark/vinilo.png"), lblCover));
        else
            lblCover.setIcon(SysUtil.getResizedIcon(R.icons("vinilo.png"), lblCover));

        panelTrackInfo.updateUI();
        updateUI();
    }

    public AudioTag getTag() {
        return element;
    }

    public void setTag(AudioTag tag) {
        this.element = tag;
        loadTrackData();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCover = new javax.swing.JLabel();
        panelTrackInfo = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblArtist = new javax.swing.JLabel();

        setBackground(java.awt.Color.white);
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.lightGray, java.awt.Color.lightGray));
        setForeground(java.awt.Color.black);
        setLayout(new java.awt.BorderLayout());

        lblCover.setBackground(java.awt.Color.white);
        lblCover.setForeground(java.awt.Color.black);
        lblCover.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(lblCover, java.awt.BorderLayout.CENTER);

        panelTrackInfo.setBackground(java.awt.Color.white);
        panelTrackInfo.setForeground(java.awt.Color.black);
        panelTrackInfo.setLayout(new java.awt.GridLayout(2, 0, 0, 3));

        lblTitle.setBackground(java.awt.Color.white);
        lblTitle.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblTitle.setForeground(java.awt.Color.black);
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("[DEFAULT TEXT]");
        lblTitle.setOpaque(true);
        panelTrackInfo.add(lblTitle);

        lblArtist.setBackground(java.awt.Color.white);
        lblArtist.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblArtist.setForeground(java.awt.Color.black);
        lblArtist.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblArtist.setText("[DEFAULT TEXT]");
        lblArtist.setOpaque(true);
        panelTrackInfo.add(lblArtist);

        add(panelTrackInfo, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblArtist;
    private javax.swing.JLabel lblCover;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel panelTrackInfo;
    // End of variables declaration//GEN-END:variables
}
