/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.orangeplayer.playerdesktop.gui.components;

import java.awt.Dimension;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import org.jaudiotagger.audio.exceptions.CannotReadException;
import org.jaudiotagger.audio.exceptions.InvalidAudioFrameException;
import org.jaudiotagger.audio.exceptions.ReadOnlyFileException;
import org.jaudiotagger.tag.FieldKey;
import org.jaudiotagger.tag.TagException;
import org.muplayer.audio.AudioTag;
import org.orangeplayer.playerdesktop.R;
import org.orangeplayer.playerdesktop.sys.SysUtil;

/**
 *
 * @author martin
 */
public class FileCard extends ItemPanel<File> {

    private static final Dimension coverSize = new Dimension(64, 64);
    
    public FileCard(File file) {
        super(file);
        initComponents();
        configUI();
        loadAudioData();
        setVisible(true);
    }
    
    // cuidado al traer de sesion el playercontroller porque puede
    // causar incongruencias si no se ha actualizado de afuera
    private void loadAudioData() {
        if (element.isDirectory()) {
            lblCover.setIcon(R.icons("folder.png"));
            lblCover.updateUI();
            lblTitle.setText(element.getName());
        }
        /*else {
            try {
                final AudioTag tag = new AudioTag(element);
                if (tag.hasCover())
                    lblCover.setIcon(SysUtil.getResizedIcon(new ImageIcon(tag.getCoverData()), coverSize));
                else
                    lblCover.setIcon(R.icons("folder.png"));
                lblCover.updateUI();
                
                String title = tag.getTag(FieldKey.TITLE);
                lblTitle.setText(title == null ? element.getName() : title);
                
            } catch (TagException | ReadOnlyFileException | CannotReadException | InvalidAudioFrameException | IOException ex) {
                Logger.getLogger(FileCard.class.getName()).log(Level.SEVERE, null, ex);
            }
        }*/
    }
    
    @Override
    protected void configUI() {
        //setBorder(new MatteBorder(3, 3, 5, 5, R.colors.CARD_BORDER_COLOR));
        //ComponentUtil.configBackgrounds(this, R.colors.CARD_COLOR);
    }

    public JLabel getLblCover() {
        return lblCover;
    }

    public JLabel getLblTitle() {
        return lblTitle;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCover = new javax.swing.JLabel();
        panelInfo = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();

        setBackground(java.awt.Color.white);

        lblCover.setBackground(java.awt.Color.white);
        lblCover.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCover.setOpaque(true);

        panelInfo.setBackground(java.awt.Color.white);
        panelInfo.setLayout(new java.awt.GridLayout(1, 1));

        lblTitle.setBackground(java.awt.Color.white);
        lblTitle.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblTitle.setText("[No Song]");
        lblTitle.setOpaque(true);
        panelInfo.add(lblTitle);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(lblCover, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(panelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCover, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(panelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCover;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel panelInfo;
    // End of variables declaration//GEN-END:variables

}
