/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.orangeplayer.playerdesktop.gui.components;

import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.border.MatteBorder;
import org.jaudiotagger.tag.FieldKey;
import org.muplayer.audio.AudioTag;
import org.orangeplayer.playerdesktop.R;
import org.orangeplayer.playerdesktop.gui.util.ComponentUtil;
import org.orangeplayer.playerdesktop.sys.Session;
import org.orangeplayer.playerdesktop.sys.SessionKey;
import org.orangeplayer.playerdesktop.sys.SysUtil;

/**
 *
 * @author martin
 */
public class TrackCard extends ItemPanel<AudioTag> {

    private static final Dimension coverSize = new Dimension(64, 64);
    
    public TrackCard(AudioTag track) {
        super(track);
        initComponents();
        configUI();
        loadAudioData();
        setVisible(true);
    }
    
    private void loadAudioData() {
        if (element.hasCover()) {
            final byte[] coverData = element.getCoverData();
            lblCover.setIcon(SysUtil.getResizedIcon(new ImageIcon(coverData), coverSize));
        }
        else if ((boolean)Session.getInstance().get(SessionKey.DARK_MODE)) 
            lblCover.setIcon(SysUtil.getResizedIcon(R.icons("dark/vinilo.png"), coverSize));
        else
            lblCover.setIcon(SysUtil.getResizedIcon(R.icons("vinilo.png"), coverSize));
        
        lblCover.updateUI();
        final String title = element.getTag(FieldKey.TITLE);
        final String album = element.getTag(FieldKey.ALBUM);
        final String artist = element.getTag(FieldKey.ARTIST);
        
        lblTitle.setText(title == null || title.equals("") ? 
                element.getFileSource().getName() : 
                title);
                
        lblAlbum.setText(album == null || album.equals("") ? "Desconocido" : album);
        lblArtist.setText(artist == null || artist.equals("") ? "Desconocido" : artist);
        panelInfo.updateUI();
    }
    
    @Override
    protected void configUI() {
        //setBorder(new MatteBorder(3, 3, 5, 5, R.colors.CARD_BORDER_COLOR));
        //ComponentUtil.configBackgrounds(this, R.colors.CARD_COLOR);
    }

    public JLabel getLblAlbum() {
        return lblAlbum;
    }

    public JLabel getLblArtist() {
        return lblArtist;
    }

    public JLabel getLblCover() {
        return lblCover;
    }

    public JLabel getLblTitle() {
        return lblTitle;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCover = new javax.swing.JLabel();
        panelInfo = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblAlbum = new javax.swing.JLabel();
        lblArtist = new javax.swing.JLabel();

        setBackground(java.awt.Color.white);

        lblCover.setBackground(java.awt.Color.white);
        lblCover.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCover.setOpaque(true);

        panelInfo.setBackground(java.awt.Color.white);
        panelInfo.setLayout(new java.awt.GridLayout(3, 1));

        lblTitle.setBackground(java.awt.Color.white);
        lblTitle.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblTitle.setText("[No Song]");
        lblTitle.setOpaque(true);
        panelInfo.add(lblTitle);

        lblAlbum.setBackground(java.awt.Color.white);
        lblAlbum.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblAlbum.setText("[No Song]");
        lblAlbum.setOpaque(true);
        panelInfo.add(lblAlbum);

        lblArtist.setBackground(java.awt.Color.white);
        lblArtist.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblArtist.setText("[No Song]");
        lblArtist.setOpaque(true);
        panelInfo.add(lblArtist);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(lblCover, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(panelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCover, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(panelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAlbum;
    private javax.swing.JLabel lblArtist;
    private javax.swing.JLabel lblCover;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel panelInfo;
    // End of variables declaration//GEN-END:variables

}
